name: clique_king_model
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  bloc: ^8.1.2
  bloc_test: ^9.1.4
  dotenv: ^4.1.0
  equatable: ^2.0.5
  firedart: ^0.9.7
  hive: ^2.2.3
  meta: ^1.10.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
